language: haskell
sudo: false

env:
  - GHCVER=7.10.2 STACK_YAML=stack.yaml

cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p $HOME/.local/bin
  - export STACK_VERSION=0.1.8.0
  - export PATH=$HOME/.local/bin:$PATH
  - export STACK_FULLVERSION=stack-$STACK_VERSION-linux-x86_64
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v$STACK_VERSION/$STACK_FULLVERSION.tar.gz | tar xz --strip-components 1 -C ~/.local/bin $STACK_FULLVERSION/stack;
  - chmod a+x $HOME/.local/bin/stack
  - stack --version

install:
  - stack setup --no-terminal

script:
  - stack build --no-terminal
  - stack test --coverage
  - cabal configure --enable-tests --enable-library-coverage
  - cabal test

after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls hspec
