language: c
sudo: false

env:
  - GHCVER=7.10.2 STACK_YAML=stack.yaml CABALVER=1.22

addons:
  apt:
    sources:
      hvr-ghc
    packages:
      - cabal-install-1.22
      - ghc-7.10.2
      - libgtk-3-dev

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.stack
    - $HOME/.ghc

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

install:
  - stack setup --no-terminal

script:
  - stack test --no-terminal --coverage

after_script:
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.3.0/shc-linux-x64-7.10.2.tar.bz2 | tar -xj
  - ./shc moonbase test

notifications:
  email: false
